"""Alembic script template.

Revision ID: ef43289b387f
Revises: 001_initial
Create Date: 2026-03-01 17:07:05.940414
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef43289b387f'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_material_variants_external_id'), ['external_id'], unique=True)

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_materials_external_id'), ['external_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_external_id'))
        batch_op.drop_column('external_id')

    with op.batch_alter_table('material_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_variants_external_id'))
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
